package handler

import (
	"aletheiaware.com/authgo"
	"aletheiaware.com/authgo/authtest"
	"aletheiaware.com/authgo/handler"
	"github.com/stretchr/testify/assert"
	"html/template"
	"io"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strings"
	"testing"
)

func AccountRecovery(t *testing.T, a func(*testing.T) authgo.Authenticator) {
	tmpl, err := template.New("account-recovery.go.html").Parse(`{{.Error}}`)
	assert.Nil(t, err)
	t.Run("Redirects When Signed In", func(t *testing.T) {
		auth := a(t)
		authtest.NewTestAccount(t, auth)
		token, _ := authtest.SignIn(t, auth)
		mux := http.NewServeMux()
		handler.AttachHandlers(auth, mux, tmpl)
		request := httptest.NewRequest(http.MethodGet, "/account-recovery", nil)
		request.AddCookie(authgo.NewSignInSessionCookie(token))
		response := httptest.NewRecorder()
		mux.ServeHTTP(response, request)
		result := response.Result()
		assert.Equal(t, http.StatusFound, result.StatusCode)
		u, err := result.Location()
		assert.Nil(t, err)
		assert.Equal(t, "/account", u.String())
	})
	t.Run("Returns 200 When Not Signed In", func(t *testing.T) {
		auth := a(t)
		mux := http.NewServeMux()
		handler.AttachHandlers(auth, mux, tmpl)
		request := httptest.NewRequest(http.MethodGet, "/account-recovery", nil)
		response := httptest.NewRecorder()
		mux.ServeHTTP(response, request)
		result := response.Result()
		assert.Equal(t, http.StatusOK, result.StatusCode)
		body, err := io.ReadAll(result.Body)
		assert.Nil(t, err)
		assert.Empty(t, string(body))
		cookies := result.Cookies()
		assert.Equal(t, 1, len(cookies))
		assert.Equal(t, authgo.COOKIE_ACCOUNT_RECOVERY, cookies[0].Name)
	})
	t.Run("Redirects When Email Is Registered", func(t *testing.T) {
		auth := a(t)
		acc := authtest.NewTestAccount(t, auth)
		assert.Nil(t, auth.SetEmailVerified(acc.Email, true))
		mux := http.NewServeMux()
		handler.AttachHandlers(auth, mux, tmpl)
		request := httptest.NewRequest(http.MethodGet, "/account-recovery", nil)
		response := httptest.NewRecorder()
		mux.ServeHTTP(response, request)
		result := response.Result()
		assert.Equal(t, http.StatusOK, result.StatusCode)
		body, err := io.ReadAll(result.Body)
		assert.Nil(t, err)
		assert.Empty(t, string(body))
		cookies := result.Cookies()
		assert.Equal(t, 1, len(cookies))
		assert.Equal(t, authgo.COOKIE_ACCOUNT_RECOVERY, cookies[0].Name)
		reader := strings.NewReader("email=" + authtest.TEST_EMAIL)
		request = httptest.NewRequest(http.MethodPost, "/account-recovery", reader)
		request.Header.Set("Content-Type", "application/x-www-form-urlencoded")
		request.AddCookie(cookies[0])
		response = httptest.NewRecorder()
		mux.ServeHTTP(response, request)
		result = response.Result()
		assert.Equal(t, http.StatusFound, result.StatusCode)
		body, err = io.ReadAll(result.Body)
		assert.Nil(t, err)
		u, err := result.Location()
		assert.Nil(t, err)
		assert.Equal(t, "/account-recovery-verification", u.String())
	})
	t.Run("Redirects When Email Is Not Registered", func(t *testing.T) {
		auth := a(t)
		mux := http.NewServeMux()
		handler.AttachHandlers(auth, mux, tmpl)
		request := httptest.NewRequest(http.MethodGet, "/account-recovery", nil)
		response := httptest.NewRecorder()
		mux.ServeHTTP(response, request)
		result := response.Result()
		assert.Equal(t, http.StatusOK, result.StatusCode)
		body, err := io.ReadAll(result.Body)
		assert.Nil(t, err)
		assert.Empty(t, string(body))
		cookies := result.Cookies()
		assert.Equal(t, 1, len(cookies))
		assert.Equal(t, authgo.COOKIE_ACCOUNT_RECOVERY, cookies[0].Name)
		reader := strings.NewReader("email=" + authtest.TEST_EMAIL)
		request = httptest.NewRequest(http.MethodPost, "/account-recovery", reader)
		request.Header.Set("Content-Type", "application/x-www-form-urlencoded")
		request.AddCookie(cookies[0])
		response = httptest.NewRecorder()
		mux.ServeHTTP(response, request)
		result = response.Result()
		assert.Equal(t, http.StatusFound, result.StatusCode)
		u, err := result.Location()
		assert.Nil(t, err)
		assert.Equal(t, "/account-recovery", u.String())

		// Subsequent Get request should show error
		request = httptest.NewRequest(http.MethodGet, "/account-recovery", nil)
		request.AddCookie(cookies[0])
		response = httptest.NewRecorder()
		mux.ServeHTTP(response, request)
		result = response.Result()
		assert.Equal(t, http.StatusOK, result.StatusCode)
		body, err = io.ReadAll(result.Body)
		assert.Nil(t, err)
		assert.Equal(t, authgo.ErrEmailNotRegistered.Error(), string(body))
	})
	t.Run("Redirects When Post Requested Before Get", func(t *testing.T) {
		auth := a(t)
		mux := http.NewServeMux()
		handler.AttachHandlers(auth, mux, tmpl)
		reader := strings.NewReader("email=" + authtest.TEST_EMAIL)
		request := httptest.NewRequest(http.MethodPost, "/account-recovery", reader)
		request.Header.Set("Content-Type", "application/x-www-form-urlencoded")
		response := httptest.NewRecorder()
		mux.ServeHTTP(response, request)
		result := response.Result()
		assert.Equal(t, http.StatusFound, result.StatusCode)
		u, err := result.Location()
		assert.Nil(t, err)
		assert.Equal(t, "/account-recovery", u.String())
	})
}

func AccountRecoveryVerification(t *testing.T, a func(*testing.T) authgo.Authenticator) {
	tmpl, err := template.New("account-recovery-verification.go.html").Parse(`{{.Error}}`)
	assert.Nil(t, err)
	t.Run("Returns 200 When Recovering", func(t *testing.T) {
		auth := a(t)
		authtest.NewTestAccount(t, auth)
		token, err := auth.NewAccountRecoverySession()
		assert.Nil(t, err)
		mux := http.NewServeMux()
		handler.AttachHandlers(auth, mux, tmpl)
		request := httptest.NewRequest(http.MethodGet, "/account-recovery-verification", nil)
		request.AddCookie(authgo.NewAccountRecoverySessionCookie(token))
		response := httptest.NewRecorder()
		mux.ServeHTTP(response, request)
		result := response.Result()
		assert.Equal(t, http.StatusOK, result.StatusCode)
		body, err := io.ReadAll(result.Body)
		assert.Nil(t, err)
		assert.Empty(t, string(body))
	})
	t.Run("Redirects When Not Recovering", func(t *testing.T) {
		auth := a(t)
		mux := http.NewServeMux()
		handler.AttachHandlers(auth, mux, tmpl)
		request := httptest.NewRequest(http.MethodGet, "/account-recovery-verification", nil)
		response := httptest.NewRecorder()
		mux.ServeHTTP(response, request)
		result := response.Result()
		assert.Equal(t, http.StatusFound, result.StatusCode)
		u, err := result.Location()
		assert.Nil(t, err)
		assert.Equal(t, "/account-recovery", u.String())
	})
	t.Run("Redirects After Recovery", func(t *testing.T) {
		auth := a(t)
		authtest.NewTestAccount(t, auth)
		token, err := auth.NewAccountRecoverySession()
		assert.Nil(t, err)
		err = auth.SetAccountRecoverySessionEmail(token, authtest.TEST_EMAIL)
		assert.Nil(t, err)
		err = auth.SetAccountRecoverySessionUsername(token, authtest.TEST_USERNAME)
		assert.Nil(t, err)
		err = auth.SetAccountRecoverySessionChallenge(token, authtest.TEST_CHALLENGE)
		assert.Nil(t, err)
		mux := http.NewServeMux()
		handler.AttachHandlers(auth, mux, tmpl)
		values := url.Values{}
		values.Add("verification", authtest.TEST_CHALLENGE)
		reader := strings.NewReader(values.Encode())
		request := httptest.NewRequest(http.MethodPost, "/account-recovery-verification", reader)
		request.Header.Set("Content-Type", "application/x-www-form-urlencoded")
		request.AddCookie(authgo.NewAccountRecoverySessionCookie(token))
		response := httptest.NewRecorder()
		mux.ServeHTTP(response, request)
		result := response.Result()
		assert.Equal(t, http.StatusFound, result.StatusCode)
		cookies := result.Cookies()
		assert.Equal(t, 1, len(cookies))
		assert.Equal(t, authgo.COOKIE_SIGN_IN, cookies[0].Name)
		u, err := result.Location()
		assert.Nil(t, err)
		assert.Equal(t, "/account-password", u.String())
		username, authenticated, errmsg, ok := auth.LookupSignInSession(cookies[0].Value)
		assert.Equal(t, authtest.TEST_USERNAME, username)
		assert.True(t, authenticated)
		assert.Empty(t, errmsg)
		assert.True(t, ok)
	})
	t.Run("Redirects When Challenge Is Incorrect", func(t *testing.T) {
		auth := a(t)
		token, err := auth.NewAccountRecoverySession()
		assert.Nil(t, err)
		cookie := authgo.NewAccountRecoverySessionCookie(token)
		err = auth.SetAccountRecoverySessionChallenge(token, authtest.TEST_CHALLENGE)
		assert.Nil(t, err)
		mux := http.NewServeMux()
		handler.AttachHandlers(auth, mux, tmpl)
		values := url.Values{}
		values.Add("verification", "1234abcd")
		reader := strings.NewReader(values.Encode())
		request := httptest.NewRequest(http.MethodPost, "/account-recovery-verification", reader)
		request.Header.Set("Content-Type", "application/x-www-form-urlencoded")
		request.AddCookie(cookie)
		response := httptest.NewRecorder()
		mux.ServeHTTP(response, request)
		result := response.Result()
		assert.Equal(t, http.StatusFound, result.StatusCode)
		u, err := result.Location()
		assert.Nil(t, err)
		assert.Equal(t, "/account-recovery-verification", u.String())

		// Subsequent Get request should show error
		request = httptest.NewRequest(http.MethodGet, "/account-recovery-verification", nil)
		request.AddCookie(cookie)
		response = httptest.NewRecorder()
		mux.ServeHTTP(response, request)
		result = response.Result()
		assert.Equal(t, http.StatusOK, result.StatusCode)
		body, err := io.ReadAll(result.Body)
		assert.Nil(t, err)
		assert.Equal(t, authgo.ErrIncorrectEmailVerification.Error(), string(body))
	})
}
